
services:
  hadith-api:
    image: hadith-api
    container_name: testing
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    networks:
      - hadith-network

networks:
    hadith-network:
         driver: bridge 
