
services:
  hadith-api:
    image: abdallahmohamed7/hadith-api:latest
    container_name: testing
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hadithd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - hadith-network
  db:
     image: mysql:8
     container_name: testingdb
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=hadithd
     networks:
       -  hadith-network
networks:
    hadith-network:
         driver: bridge
